### ISSUE TITLE
TypeError: ParamPaCMAP.fit() got an unexpected keyword argument 'y'

### ISSUE THREAD

**Issue by arianaqyp** [hyhuang00/ParamRepulsor#3]
Hi,

I encountered a TypeError when using fit_transform():

TypeError: ParamPaCMAP.fit() got an unexpected keyword argument 'y'

**Comment by mathematicalmichael** [comment]
this is addressed in my branch/PR: #2

**Comment by hyhuang00** [comment]
Thank you for your interest in our work! I think the currently merged PR #2 should have fixed most of the issues. Feel free to reopen it if you still encounter this issue!
